#!/usr/bin/env node
var debug = require('debug')('devbom');
var https = require('https');
var fs = require('fs');
var app = require('./app');
var onshape = require('./routes/onshape');

app.set('port', process.env.PORT || 4052);
onshape.setProtocol('https');

var options = {
    pfx:      fs.readFileSync('ssl/apps_onshape_com.pfx'),
    requestCert:        false,
    rejectUnauthorized: false
};



var server = https.createServer(options, app);
server.listen(app.get('port'), function() {
  console.log('Express server listening on HTTPS port ' + app.get('port'));
});

