#!/usr/bin/env node
var debug = require('debug')('devconsole');
var http = require('http');
var fs = require('fs');
var app = require('./app');
var onshape = require('./routes/onshape');

app.set('port', process.env.PORT || 4000);
onshape.setProtocol('http');

var server = http.createServer(app);

server.listen(app.get('port'), function() {
    console.log('Express server listening on HTTP port ' + app.get('port'));
    });
